---
title: "did"
author: "Mitja Bof"
date: '2022-12-05'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(infer)
```

```{r}
mun88 <- read_delim("data/storico_amministratori_comuni31121992_0.csv", 
                    delim = ";") |> rowwise() |>
  mutate(anno_nomina = as.integer(str_split(DATA_NOMINA, "/")[[1]][3]),
         mese_nomina = as.integer(str_split(DATA_NOMINA, "/")[[1]][2]),
         anno_nascita = as.integer(str_split(DATA_NASCITA, "/")[[1]][3]),
         anno_elezione = as.integer(str_split(DATA_ELEZIONE, "/")[[1]][3]))

mun88 <- mun88 |> inner_join(mun_refs93, by = "DESCRIZIONE_COMUNE")

mun87 <- read_delim("data/storico_amministratori_comuni31121991_0.csv", 
                    delim = ";") |> rowwise() |>
  mutate(anno_nomina = as.integer(str_split(DATA_NOMINA, "/")[[1]][3]),
         mese_nomina = as.integer(str_split(DATA_NOMINA, "/")[[1]][2]),
         anno_nascita = as.integer(str_split(DATA_NASCITA, "/")[[1]][3]),
         anno_elezione = as.integer(str_split(DATA_ELEZIONE, "/")[[1]][3]))

mun87 <- mun87 |> inner_join(mun_refs92, by = "DESCRIZIONE_COMUNE")

mun_pre <- bind_rows(mun87, mun88)

```

```{r}
mun_pre <- mun_pre |>
  mutate(DESCRIZIONE_COMUNE = if_else(DESCRIZIONE_COMUNE == "CASTRO" & 
                                        DESCRIZIONE_REGIONE == "LOMBARDIA",
                                      "CASTRO (LOMBARDIA)", DESCRIZIONE_COMUNE))

mun_pre <- mun_pre |> 
  mutate(geo = case_when(
    DESCRIZIONE_REGIONE %in% south ~ "South",
    DESCRIZIONE_REGIONE %in% center ~ "Center",
    DESCRIZIONE_REGIONE %in% north ~ "North",
  ))

mun_pre <- mun_pre |>
  mutate(sesso_bin = if_else(SESSO == "M", 0, 1)) |>
  within(reform <- relevel(as.factor(reform), ref = "Pre-reform")) |>
  within(geo <- relevel(as.factor(geo), ref = "North"))

mun_prop_counc_pre <- mun_pre |> 
  filter(LIVELLO_CARICA == 120) |>
  group_by(DESCRIZIONE_COMUNE) |>
  summarize(prop_female = mean(sesso_bin, na.rm = TRUE),
            ref = unique(reform),
            pop = max(POPOLAZIONE_CENSITA),
            geo = unique(geo))
mun_prop_did <- mun_prop_counc |> 
  inner_join(mun_prop_counc_pre, 
             by = c("DESCRIZIONE_COMUNE", "ref")) |>
  mutate(diff = prop_female.x - prop_female.y)

```

```{r}
mun_prop_did_obs <- mun_prop_did |> specify(response = diff, explanatory = ref) |>
  calculate(stat = "diff in means", order = c("Post-reform", "Pre-reform"))

mun_prop_did_boot <- mun_prop_did |> specify(response = diff, explanatory = ref) |>
  generate(reps = 1000, type = "bootstrap") |>
  calculate(stat = "diff in means", order = c("Post-reform", "Pre-reform"))

did_boot_viz <- visualize(mun_prop_did_boot) + 
  shade_pvalue(obs_stat = 0, direction = "less") + 
  labs(x = "Difference in Differences",
       y = "", 
       title = "DiD Simulation-Based Bootstrap Distribution")

save(did_boot_viz, mun_prop_did_obs, file = "output/did-boots.RData")
```

Regression

```{r}
did_reg <- lm(diff ~ ref*geo.x, data = mun_prop_did)
summary(did_reg)
```
DiD Viz

```{r}
did_summ <- mun_prop_did |>
  group_by(geo.x, ref) |>
  summarize(Before = mean(prop_female.y),
            After = mean(prop_female.x))
did_sum_viz <- did_summ |> pivot_longer(Before:After, names_to = "period",
                         values_to = "value") |>
  ggplot(aes(x = period, y = value)) + 
  geom_line(aes(color = ref, group = ref), size = 1.3) + 
  scale_x_discrete(limits = c("Before", "After")) + 
  theme_classic() + 
  labs(x = "Period",
       y = "Share of female council members",
       title = "Difference in Differences") +
  facet_wrap(~ geo.x)
save(did_summ, did_sum_viz, file = "output/did-viz.RData")
```

