---
title: "index-code"
author: "Mitja Bof"
date: '2022-12-04'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
```

**Important: run all of main-analysis.rmd first**

Table with findings

```{r}
mun_gender_may |> 
  bind_cols(select(mun_gender_sec, -SESSO)) |>
  bind_cols(select(mun_gender_cons, -SESSO)) |>
  knitr::kable(col.names = 
          c("Gender", "Post", "Pre", "Diff.",
            "Post", "Pre", "Diff.",
            "Post", "Pre", "Diff."),
        digits = 2) |>
  add_header_above(c(" ", "Mayors" = 3, "Local secretaries" = 3, "Council members" = 3)) |> 
  kable_styling(position = "center") |>
  saveRDS("output/main-table.rds")
```
Impact barplot

```{r}
mun_gender_may |> 
  bind_cols(select(mun_gender_sec, -SESSO)) |>
  bind_cols(select(mun_gender_cons, -SESSO)) |>
  filter(SESSO == "F") |>
  mutate(Mayors = `1...2` - `0...3`,
         LS = `1...5` - `0...6`,
         CM = `1...8` - `0...9`,) |>
  select(Mayors, LS, CM) |>
  pivot_longer(cols = Mayors:CM, names_to = "type", values_to = "impact") |>
  saveRDS("output/impact-bar.RDS")
```
Main regression tables.

```{r}
var_labs <- c(
  "(Intercept)" = "(Intercept)", "period" = "Period (Before / After)", 
  "reform" = "Year Pair (treatment)",
  "period:reform" = "Interaction (DiD)", "geoCenter" = "Central region",
  "geoSouth" = "Southern region", "pop" = "Population"
)

model_table <- modelsummary::modelsummary(
  list("All regions" = reg_did_counc, 
       "North" = rn, 
       "Center" = rc,
       "South" = rs),
  gof_map = c("nobs", "r.squared", "adj.r.squared"),
  coef_map = var_labs,
  stars = TRUE,
  fmt = "%.3f"
)

mayor_coef_map <- c("period" = "Period (Before / After)",
                    "reform" = "Year Pair (treatment)",
                    "period:reform" = "Inteaction effect (DiD)",
                    "geoCenter" = "Central region",
                    "geoSouth" = "Southern region")

mayor_table <- modelsummary::modelsummary(
  list("DiD" = reg_mayor,
       "DiD - Geographic macroarea" = reg_mayor_geo),
  gof_map = NA,
  coef_map = mayor_coef_map,
  fmt = "%.3f",
  estimate = "{estimate}",
  statistic = "{std.error} ({p.value})",
  title = "Difference in Differences - Mayor Share"
)
save(var_labs, model_table, mayor_coef_map, mayor_table, 
     file = "output/model-table.RData")
```


