---
title: "test"
author: "Mitja Bof"
date: '2022-12-03'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
mun92 <- read_delim("data/storico_amministratori_comuni31121992_0.csv", 
                    delim = ";") |> rowwise() |>
  mutate(anno_nomina = as.integer(str_split(DATA_NOMINA, "/")[[1]][3]),
         mese_nomina = as.integer(str_split(DATA_NOMINA, "/")[[1]][2]),
         anno_nascita = as.integer(str_split(DATA_NASCITA, "/")[[1]][3]),
         anno_elezione = as.integer(str_split(DATA_ELEZIONE, "/")[[1]][3]))
mun_refs92 <- mun92 |> 
  filter(DESCRIZIONE_CARICA == "Sindaco") |>
  filter(anno_elezione == 1992) |>
  mutate(reform = "Pre-reform") |>
  select(DESCRIZIONE_COMUNE, reform)
mun92 <- mun92 |> inner_join(mun_refs92, by = "DESCRIZIONE_COMUNE")

mun93 <- read_delim("data/storico_amministratori_comuni31121993_0.csv", 
                    delim = ";") |> rowwise() |>
  mutate(anno_nomina = as.integer(str_split(DATA_NOMINA, "/")[[1]][3]),
         mese_nomina = as.integer(str_split(DATA_NOMINA, "/")[[1]][2]),
         anno_nascita = as.integer(str_split(DATA_NASCITA, "/")[[1]][3]),
         anno_elezione = as.integer(str_split(DATA_ELEZIONE, "/")[[1]][3]))
mun_refs93 <- mun93 |> 
  filter(DESCRIZIONE_CARICA == "Sindaco") |>
  filter(anno_elezione == 1993) |>
  mutate(reform = "Post-reform") |>
  select(DESCRIZIONE_COMUNE, reform)
mun93 <- mun93 |> inner_join(mun_refs93, by = "DESCRIZIONE_COMUNE")
```

```{r}
mun <- bind_rows(mun92, mun93)
rm(mun92)
rm(mun93)
sub <- mun |> 
  select(CODICE_PROVINCIA, COGNOME, NOME, LIVELLO_CARICA, DATA_NOMINA)

dup <- !duplicated(sub)
rm(sub)
mun <- mun[dup,]
rm(dup)
```



```{r}
vars <- c("DESCRIZIONE_REGIONE", "CODICE_COMUNE", "DESCRIZIONE_COMUNE",
          "POPOLAZIONE_CENSITA", "MAGGIORITARIO_PROPORZIONALE", 
          "CONSIGLIERI_SPETTANTI","SESSO", "LIVELLO_CARICA",
          "DESCRIZIONE_CARICA", "DATA_CESSAZIONE",
          "TITOLO_DI_STUDIO", "anno_nomina", "mese_nomina", 
          "anno_nascita", "anno_elezione")

south <- c("ABRUZZO", "MOLISE", "CAMPANIA", "PUGLIA", "BASILICATA", "CALABRIA",
           "SICILIA", "SARDEGNA")
center <- c("TOSCANA", "UMBRIA", "MARCHE", "LAZIO")

north <- c("PIEMONTE", "VALLE D'AOSTA", "LOMBARDIA", "TRENTINO-ALTO ADIGE", 
           "VENETO", "FRIULI-VENEZIA GIULIA", "LIGURIA", "EMILIA ROMAGNA")

mun_el <- mun |>
  select(vars) |> filter(anno_elezione == 1992 | anno_elezione == 1993)
mun_nom <- mun |>
  select(vars) |> filter(anno_nomina == 1992 | anno_nomina == 1993)

mun <- mun |> 
  mutate(geo = case_when(
    DESCRIZIONE_REGIONE %in% south ~ "South",
    DESCRIZIONE_REGIONE %in% center ~ "Center",
    DESCRIZIONE_REGIONE %in% north ~ "North",
  ))
```

Pre-post reform variable

```
mun_refs <- mun |> 
  filter(DESCRIZIONE_CARICA == "Sindaco") |>
  mutate(reform = if_else(anno_elezione <= 1992, "Pre-reform", "Post-reform")) |>
  filter(anno_elezione == 1992 | anno_elezione == 1993) |>
  select(DESCRIZIONE_COMUNE, reform)

sub <- mun_refs |> 
  select(DESCRIZIONE_COMUNE)
tmp <- duplicated(sub)
rm(sub)
both_years_muns <- mun_refs[tmp,]
mun_refs <- mun_refs[!tmp,]
rm(tmp)

mun_refs

mun <- mun |>
  filter(DESCRIZIONE_COMUNE %in% mun_refs$DESCRIZIONE_COMUNE) |>
  inner_join(mun_refs)
```


Gender all

```{r}
mun_gender_all <- mun |> 
  drop_na(SESSO) |>
  group_by(reform, SESSO) |>
  summarize(n = n()) |>
  mutate(prop = n / sum(n)) |>
  select(-n) |>
  pivot_wider(names_from = reform, values_from = prop)
mun_gender_all
```

Gender cons

```{r}
mun_gender_cons <- mun |>
  filter(LIVELLO_CARICA == 120) |>
  drop_na(SESSO) |>
  group_by(reform, SESSO) |>
  summarize(n = n()) |>
  mutate(prop = n / sum(n)) |>
  select(-n) |>
  pivot_wider(names_from = reform, values_from = prop)
mun_gender_cons
```

Gender mayor

```{r}
mun_gender_may <- mun |>
  filter(LIVELLO_CARICA == 10) |>
  drop_na(SESSO) |>
  group_by(reform, SESSO) |>
  summarize(n = n()) |>
  mutate(prop = n / sum(n)) |>
  select(-n) |>
  pivot_wider(names_from = reform, values_from = prop)
mun_gender_may
```
Gender secretaries

```{r}
mun_gender_sec <- mun |>
  filter(LIVELLO_CARICA == 50) |>
  drop_na(SESSO) |>
  group_by(reform, SESSO) |>
  summarize(n = n()) |>
  mutate(prop = n / sum(n)) |>
  select(-n) |>
  pivot_wider(names_from = reform, values_from = prop) |>
  relocate(`Post-reform`, .after = SESSO)
mun_gender_sec
```

Covariate balance - population

```{r}
cov_bal_pop <- mun |>
  group_by(reform) |>
  summarize(mean_pop = mean(POPOLAZIONE_CENSITA, na.rm = TRUE))
cov_bal_pop
```

Regression model


```{r}
mun <- mun |>
  mutate(sesso_bin = if_else(SESSO == "M", 0, 1)) |>
  within(reform <- relevel(as.factor(reform), ref = "Pre-reform")) |>
  within(geo <- relevel(as.factor(geo), ref = "North"))

mun_mayor <- mun |>
  filter(DESCRIZIONE_CARICA == "Sindaco" & 
           (anno_elezione == 1992 | anno_elezione == 1993))
```

```{r}
lr <- glm(sesso_bin ~ reform + POPOLAZIONE_CENSITA + geo, data = mun_mayor, family = binomial)
summary(lr)
broom::tidy(lr)
confint(lr)
odds_ratio <- exp(coef(lr))
odds_ratio
```

Within municipality

```{r}
mun <- mun |>
  mutate(DESCRIZIONE_COMUNE = if_else(DESCRIZIONE_COMUNE == "CASTRO" & 
                                        DESCRIZIONE_REGIONE == "LOMBARDIA",
                                      "CASTRO (LOMBARDIA)", DESCRIZIONE_COMUNE))

mun_prop_counc <- mun |> 
  filter(LIVELLO_CARICA == 120) |>
  group_by(DESCRIZIONE_COMUNE) |>
  summarize(prop_female = mean(sesso_bin, na.rm = TRUE),
            ref = unique(reform),
            pop = max(POPOLAZIONE_CENSITA),
            geo = unique(geo))
```


Regression on prop_female - council members

```{r}
reg_prop_counc <- lm(prop_female ~ ref + pop + geo, data = mun_prop_counc)
summary(reg_prop_counc)
```

Regression on prop_female - local secretaries

```{r}
mun_prop_sec <- mun |> 
  filter(LIVELLO_CARICA == 50) |>
  group_by(DESCRIZIONE_COMUNE) |>
  summarize(prop_female = mean(sesso_bin, na.rm = TRUE),
            ref = unique(reform),
            pop = max(POPOLAZIONE_CENSITA),
            geo = unique(geo))
reg_prop_sec <- lm(prop_female ~ ref + pop + geo, data = mun_prop_sec)
summary(reg_prop_sec)
```


